Vagrant.configure(2) do |config|
  
  config.vm.box = 'bento/ubuntu-20.04'
  config.vm.provider "virtualbox" do |vb|
     vb.name = "jenkins-server"
     vb.cpus = 3
     vb.memory = "3072"
  end
  config.vm.network "private_network", ip: "192.168.56.6"
	config.vm.network "public_network", bridge: "enp2s0", use_dhcp_assigned_default_route: true
end
