Vagrant.configure(2) do |config|
  
  config.vm.box = 'bento/ubuntu-20.04'
  config.vm.provider "virtualbox" do |vb|
     vb.name = "gitlab-server"
     vb.cpus = 3
     vb.memory = "3072"
  end
  config.vm.network "private_network", ip: "192.168.56.3"
	config.vm.network "public_network", bridge: "enp2s0", use_dhcp_assigned_default_route: true
	config.vm.provision "shell", run: "always", inline: <<-SHELL
		sudo sed -i '1 s/^.*$/duy-gitlab/' /etc/hostname
		sudo mkdir -p /home/app-installed/gitlab-ce
		sudo apt-get update
		sudo apt-get upgrade -y
		sudo apt-get install -y curl openssh-server ca-certificates tzdata perl
		sudo curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
		sudo apt-get install -y gitlab-ce
		sudo gitlab-ctl reconfigure
		sudo mkdir /home/app-installed/gitlab-ce/certs
		sudo mkdir /etc/gitlab/ssl
		sudo mkdir -p /data/{backups,git-data}
		sudo mkdir /home/app-installed/docker
		sudo apt-get update
		sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
		sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
		sudo echo \
				"deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
				$(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
		sudo apt-get update
		sudo apt-get install -y docker-ce docker-ce-cli containerd.io
		sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
		sudo chmod +x /usr/local/bin/docker-compose
		sudo mkdir -p /home/app-installed/registry/certs/
		sudo mkdir -p /etc/docker/certs.d/gitlab.duy.com:5000/
		sudo mkdir -p /etc/docker/certs.d/gitlab.duy.com:5050/
SHELL

	config.vm.provision "file", source: "./gitlab.rb", destination: "/tmp/gitlab.rb"
	config.vm.provision "file", source: "./hosts", destination: "/tmp/hosts"
	config.vm.provision "file", source: "./ssl/gitlab.duy.com.crt", destination: "/tmp/gitlab.duy.com.crt"
	config.vm.provision "file", source: "./ssl/gitlab.duy.com.key", destination: "/tmp/gitlab.duy.com.key"
	config.vm.provision "file", source: "./docker-compose.yml", destination: "/tmp/docker-compose.yml"
	config.vm.provision "file", source: "./ssl/rootCA.crt", destination: "/tmp/rootCA.crt"
	
	config.vm.provision "shell", run: "always", inline: <<-SHELL
		yes | sudo cp -rf /tmp/gitlab.rb /etc/gitlab/
		yes | sudo cp -rf /tmp/hosts /etc/
		sudo cp /tmp/gitlab.duy.com.crt /home/app-installed/gitlab-ce/certs/
		sudo cp /tmp/gitlab.duy.com.key /home/app-installed/gitlab-ce/certs/
		sudo cp /tmp/docker-compose.yml /home/app-installed/registry/
		sudo cp /home/app-installed/gitlab-ce/certs/gitlab.duy.com.crt /home/app-installed/gitlab-ce/certs/gitlab.duy.com.key /etc/gitlab/ssl/
		sudo cp /home/app-installed/gitlab-ce/certs/gitlab.duy.com.crt /home/app-installed/gitlab-ce/certs/gitlab.duy.com.key /home/app-installed/registry/certs/
		sudo gitlab-ctl reconfigure
		cd /home/app-installed/registry
		sudo docker compose up -d
		sudo cp /etc/gitlab/ssl/gitlab.duy.com.crt /etc/docker/certs.d/gitlab.duy.com:5000/ca.crt
		sudo cp /etc/gitlab/ssl/gitlab.duy.com.crt /etc/docker/certs.d/gitlab.duy.com:5050/ca.crt
		sudo systemctl restart docker
		sudo gitlab-ctl reconfigure
		sudo gitlab-ctl restart nginx
		printf 'duy12345\nduy12345\n' | sudo gitlab-rake "gitlab:password:reset[root]"
		sudo cp /tmp/rootCA.crt /usr/local/share/ca-certificates/
		sudo update-ca-certificates
		printf 'user=User.create();user.name="nguyen thanh duy";user.username="duynt";user.password="duy03081998";user.email="duy.nt@zinza.com.vn";user.confirmed_at="01/01/2024";user.admin=false;user.save!;token=user.personal_access_tokens.create(scopes:["api", "read_repository", "read_user"],name:"project_token",expires_at:365.days.from_now);token.set_token("duynt381998");token.save!;\nexit\n' | sudo gitlab-rails console
		sudo curl -k --request POST --header 'PRIVATE-TOKEN: duynt381998' --header 'Content-Type: application/json' --data  '{"name": "enigma-furniture-backend", "description": "backend part of enigma project","namespace": "duynt", "initialize_with_readme": "true"}' --url 'https://gitlab.duy.com/api/v4/projects/'
		sudo curl -k --request POST --header 'PRIVATE-TOKEN: duynt381998' --header 'Content-Type: application/json' --data '{"title":"duy ssh key","key":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCZ0XFILrrbDaoSNeJLTM3EaEsW8LdX2OwXnMZf49R/4CSV703QDB8+JldeH9WBzTn3gpnz+wkOC36f2+lRnx3GH/Y3hty+m0ECmuVyrdvcdJk6Kmc3kHOGpo8zTzruzKo3eRo1s+8g2mg/81TiLvajRevXf5d1IhFSeo8PIYQ/wyyuIN505FTcpZ8qGSyX7t3JWGr7w8k29HUcBMVqvHLa6aqql23pS7DWDsX5olFPPiXtPZnLE5U60cmw/eQyi1BYYyIb8KS7Y5zrGOI12S7b7K6YHlFtiHcKB0v2Zo1LaCmMivy89VUqLqL00Gm4FErOdVhSmGGmAUUeXNe/bS9hGizRVIZRs5w/Qd59imL36uc41XQwXzcA11pd3VwCtUgf9CDGg0yOu/tkV0oVrrqHxTImmsY1MQqAAxTtE104e6heHbQnoMTPmzIyegxZfGgtz01a5YhHummbDpbHUmr0jouFTXTsoHwkYq/c36789XrligDQ+j9atbGXH9i5Dh0= duy@duy"}' --url 'https://gitlab.duy.com/api/v4/user/keys'
SHELL

	config.vm.provision "shell", run: "always", inline: <<-SHELL
		sudo gitlab-ctl status
		echo "Config  done!"
SHELL

end
