apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new-deployment
spec:
  template:
    metadata:
      name: busybox
      labels:
        name: busybox-pod
    spec:
      containers:
        - name: busybox-container
          image: busybox
  replicas: 3
  selector:
    matchLabels:
      name: busybox-pod